
[[constraint]]
  name = "github.com/andygrunwald/go-gerrit"
  version = "0.5.2"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/slothfs"

[[constraint]]
  branch = "master"
  name = "github.com/kylelemons/godebug"

[[constraint]]
  branch = "master"
  name = "github.com/sourcegraph/rpc"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.2.1"

[prune]
  go-tests = true
  unused-packages = true
